;; This logfile was generated automatically by `xindy'
;; at 29.01.2019  15:47:55
;; Indexstyle: "E:\\GitHub\\thesis-latex-template\\YG37HR0S9o", Rawindex: "E:\\GitHub\\thesis-latex-template\\IMiSedCfal", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "¨„" -> "I"
Letter-group: "†" -> "C"
Letter-group: "€®»" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€®»" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨„" -> "I"